version: "3.8"

services:
    common_web_attacks:
        image: cyberacademylabs/common_web_attacks
        hostname: common_web_attacks
        container_name: common_attacks
        ports:
            - "80:80"
        networks:
            lab-net:
                ipv4_address: 172.20.0.2

    session_puzzling:
        image: cyberacademylabs/session_puzzling
        hostname: session_puzzle
        container_name: session_puzzle
        ports:
            - "5000:5000"
        networks:
            lab-net:
                ipv4_address: 172.20.0.3

    padding_oracle:
        image: cyberacademylabs/oracle_padding
        hostname: oracle_padding
        container_name: oracle_padding
        ports:
            - "5001:5001"
        networks:
            lab-net:
                ipv4_address: 172.20.0.4

    ldap:
        image: cyberacademylabs/ldap_injection
        hostname: ldap_injection
        container_name: ldap_injection
        ports:
            - "5002:5002"
        networks:
            lab-net:
                ipv4_address: 172.20.0.5

    cors:
        image: cyberacademylabs/cors_attack
        hostname: cors_attack
        container_name: cors_attack
        ports:
            - "5003:5003"
        networks:
            lab-net:
                ipv4_address: 172.20.0.6

    url_redirect:
        image: cyberacademylabs/url_redirect
        hostname: redirect
        container_name: url_redirect
        ports:
            - "5004:5004"
        networks:
            lab-net:
                ipv4_address: 172.20.0.7

networks:
    lab-net:
        ipam:
            config:
                - subnet: 172.20.0.0/16
